services:
  postgres:
    image: postgres:17
    env_file: .env
    ports: ['5432:5432']
    volumes: ['db-data:/var/lib/postgresql/data']
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1" ]
      interval: 3s
      timeout: 3s
      retries: 30

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports: ['4000:4000']
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db-data: {}